# (i)
CREATE TABLE CUSTOMER
(
CID INT,
CNAME VARCHAR(25) NOT NULL,
LOC VARCHAR(25),
SEX VARCHAR(10),
DOB DATE
);

CREATE TABLE BANK_BRN
(
BCODE INT,
BLOC VARCHAR(25),
BSATE VARCHAR(25)
);

CREATE TABLE DEPOSIT
(
DACNO INT,
DTYPE VARCHAR(25),
DDATE DATE,
DAMT INT
);

CREATE TABLE LOAN
(
LACNO INT,
LTYPE VARCHAR(25),
LDATE DATE,
LAMT INT
);

CREATE TABLE ACCOUNTS_IN
(
BCODE INT,
CID INT
);

CREATE TABLE DEPOSITOR
(
CID INT,
DACNO INT
);

CREATE TABLE BORROWER
(
CID INT,
LACNO INT
);

# (ii)
ALTER TABLE CUSTOMER ADD PRIMARY KEY (CID);
ALTER TABLE BANK_BRN ADD PRIMARY KEY (BCODE);
ALTER TABLE DEPOSIT ADD PRIMARY KEY (DACNO);
ALTER TABLE LOAN ADD PRIMARY KEY (LACNO);

ALTER TABLE ACCOUNTS_IN ADD FOREIGN KEY (BCODE) REFERENCES BANK_BRN(BCODE);
ALTER TABLE ACCOUNTS_IN ADD FOREIGN KEY (CID) REFERENCES CUSTOMER(CID);
ALTER TABLE DEPOSITOR ADD FOREIGN KEY (CID) REFERENCES CUSTOMER(CID);
ALTER TABLE DEPOSITOR ADD FOREIGN KEY (DACNO) REFERENCES DEPOSIT(DACNO);
ALTER TABLE BORROWER ADD FOREIGN KEY (CID) REFERENCES CUSTOMER(CID);
ALTER TABLE BORROWER ADD FOREIGN KEY (LACNO) REFERENCES LOAN(LACNO);

# (iii)


# (iv)
USE BANK;
SHOW TABLES;

# (v)
DESCRIBE CUSTOMER;
DESCRIBE BANK_BRN;
DESCRIBE DEPOSIT;
DESCRIBE LOAN;
DESCRIBE ACCOUNTS_IN;
DESCRIBE DEPOSITOR;
DESCRIBE BORROWER;

# (vi)
DROP TABLE BORROWER;
DROP TABLE DEPOSITOR;
DROP TABLE ACCOUNTS_IN;
DROP TABLE LOAN;
DROP TABLE DEPOSIT;
DROP TABLE BANK_BRN;
DROP TABLE CUSTOMER;




