CREATE TABLE STUDENT_INFO
(
   SID INT UNIQUE, STUD_NAME VARCHAR(20) NOT NULL, STUD_SCORE INT DEFAULT 20,PRIMARY KEY(SID)
);
DROP TABLE STUDENT_INFO;
DROP TABLE WORKER;
DROP TABLE BONUS;
SELECT*FROM WORKER;
SELECT*FROM BONUS;
TRUNCATE TABLE STUDENT_INFO;
TRUNCATE TABLE WORKER;
TRUNCATE TABLE STUDENT_INFO;
SELECT*FROM STUDENT_INFO;
INSERT INTO STUDENT_INFO(SID,STUD_NAME,STUD_SCORE)VALUES
(1,'ANU MATHEW',100),
(2,'BHANU M',200),
(3,'VIMAL V',170),
(4,'RAJEEV MENON',180),
(5,'AMAYA JOSEPH',90),
(6,'VISHNU R NAIR',110),
(7,'INDRAGITH N S',160),
(8,'ANITHA P S',101);
UPDATE STUDENT_INFO SET STUD_SCORE = STUD_SCORE + 5 WHERE STUD_SCORE > 150;
CREATE TABLE WORKER
( 
  WORKER_ID INT, FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20),SALARY INT,
  JOINING_DATE DATE, DEPARTMENT VARCHAR(15), PRIMARY KEY(WORKER_ID)
);
CREATE TABLE BONUS
(
  WORKER_ID INT, BONUS_DATE DATE, BONUS_AMOUNT INT , FOREIGN KEY (WORKER_ID) REFERENCES WORKER(WORKER_ID)
);
INSERT INTO WORKER(WORKER_ID,FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPARTMENT)VALUES
(1,'MONIKA','ARORA',100000,'2014-02-20','HR'),
(2,'NIHARIKA','VERMA',80000,'2014-06-11','Admin'),
(3,'VISHAL','SINGHAL',300000,'2014-02-20','HR'),
(4,'AMITABH','SINGH',500000,'2014-02-20','Admin'),
(5,'VIVEK','BHATI',500000,'2014-06-11','Admin'),
(6,'VIPUL','DHIWAN',200000,'2014-06-11','Account'),
(7,'SATISH','KUMAR',75000,'2014-01-20','Account'),
(8,'GEETIKA','CHAUHAN',90000,'2014-04-11','Admin');
INSERT INTO BONUS(WORKER_ID,BONUS_DATE,BONUS_AMOUNT)VALUES
(1,'2016-02-20',5000),
(2,'2016-06-11',3000),
(3,'2016-02-20',4000),
(1,'2016-02-20',4500),
(2,'2016-06-11',3500);
SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;
SELECT * FROM WORKER ORDER BY FIRST_NAME ASC;
SELECT * FROM WORKER WHERE TRIM(FIRST_NAME) != 'VIPUL'AND TRIM(FIRST_NAME)  != 'SATISH';
SELECT * FROM WORKER WHERE FIRST_NAME NOT IN('VIPUL','SATISH');
SELECT * FROM WORKER WHERE DEPARTMENT = 'ADMIN';
SELECT * FROM WORKER WHERE SALARY BETWEEN 100000 AND 500000;
SELECT UPPER(FIRST_NAME) FROM WORKER;
SELECT SUBSTR(FIRST_NAME, 1, 3) AS SMALL FROM WORKER;
SELECT RTRIM(FIRST_NAME) FROM WORKER;
SELECT LTRIM(DEPARTMENT) FROM WORKER;
SELECT DISTINCT DEPARTMENT, LENGTH(DEPARTMENT) FROM WORKER;
SELECT REPLACE(FIRST_NAME,'A','a') AS FIRST_NAME FROM WORKER; 
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT, BONUS_AMOUNT FROM WORKER,BONUS WHERE WORKER.WORKER_ID = BONUS.WORKER_ID AND BONUS_AMOUNT > 4000;
DELETE FROM WORKER WHERE WORKER_ID=7;
SELECT * FROM WORKER;
ALTER TABLE BONUS DROP CONSTRAINT bonus_ibfk_1;
ALTER TABLE BONUS ADD CONSTRAINT BONUS_cod_na  FOREIGN KEY(WORKER_ID) REFERENCES WORKER(WORKER_ID)ON UPDATE NO ACTION ON DELETE NO ACTION;
DELETE FROM WORKER WHERE WORKER_ID = 8;
SELECT * FROM WORKER;
